export const GAME_CONFIG = {
  TOTAL_PLAYERS: 6,
  STARTING_CHIPS: 10000,
  INITIAL_SMALL_BLIND: 50,
  INITIAL_BIG_BLIND: 100,
  BLIND_INCREASE_INTERVAL: 10, // 핸드 수
  BLIND_INCREASE_MULTIPLIER: 1.5,
  AI_THINK_MIN_MS: 800,
  AI_THINK_MAX_MS: 2500,
  ANIMATION_DEAL_MS: 200,
  ANIMATION_FLIP_MS: 400,
  ANIMATION_CHIP_MS: 300,
  ANIMATION_DELAY_BETWEEN_CARDS_MS: 150,
} as const;
